stack-size-threshold = 393216
future-size-threshold = 24576
array-size-threshold = 4096
large-error-threshold = 256                 # TODO reduce me ALARA
too-many-lines-threshold = 780              # TODO reduce me to <= 100
excessive-nesting-threshold = 8
type-complexity-threshold = 250             # reduce me to ~200
cognitive-complexity-threshold = 100        # TODO reduce me ALARA

#disallowed-macros = [
#	{ path = "log::error", reason = "use tuwunel_core::error" },
#	{ path = "log::warn", reason = "use tuwunel_core::warn" },
#	{ path = "log::info", reason = "use tuwunel_core::info" },
#	{ path = "log::debug", reason = "use tuwunel_core::debug" },
#	{ path = "log::trace", reason = "use tuwunel_core::trace" },
#]

#disallowed-methods = [
#	{ path = "tokio::spawn", reason = "use and pass tuwunel_core::server::Server::runtime() to spawn from" },
#]
